### ISSUE TITLE
Run error when loading model parameters

### ISSUE THREAD

**Issue by lisongnan1982** [wangruixing/DeepUPE#37]
I had a running error. It happened during loading the model parameters. The error message is listed below. Does anyone have similar problem? 
====================================
Traceback (most recent call last):
  File "main/run.py", line 154, in <module>
    main(args)
  File "main/run.py", line 78, in main
    model_params = utils.get_model_params(sess)
  File "/home/tcl980/snli/Proj-ImgEnhance/DeepUPE/DeepUPE/main/utils.py", line 24, in get_model_params
    model_params = sess.run(params_)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'BilateralSliceApply' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: train/inference/output/slice/BilateralSliceApply = BilateralSliceApply[has_offset=true, _device="/device:GPU:0"](train/inference/output/slice/Reshape, train/inference/guide/Squeeze, train_data/shuffle_batch)]]

Caused by op u'train/inference/output/slice/BilateralSliceApply', defined at:
  File "main/run.py", line 154, in <module>
    main(args)
  File "main/run.py", line 75, in main
    tf.train.import_meta_graph(metapath)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1595, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 499, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 308, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'BilateralSliceApply' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: train/inference/output/slice/BilateralSliceApply = BilateralSliceApply[has_offset=true, _device="/device:GPU:0"](train/inference/output/slice/Reshape, train/inference/guide/Squeeze, train_data/shuffle_batch)]]

**Comment by wangruixing** [comment]
Does it seem you are trying to run the test without GPU?  What's your TensorFlow version?

**Comment by ccJia** [comment]
I met this error infomation with  wrong cuda and cudnn versions.  Compiling the 'ops' file with  cuda-8.0 and cudnn-5.1 may solve your problem.

**Comment by lisongnan1982** [comment]
I am using Tensorflow-gpu 1.1.0, cuda-8.0, cudnn-5.1. The error happened during loading the pre-trained model parameters.

**Comment by lisongnan1982** [comment]
I solved the problem by changing os.environ["CUDA_VISIBLE_DEVICES"]="1" to os.environ["CUDA_VISIBLE_DEVICES"]="0" in run.py. If you have two GPU then maybe it's not necessary.
