### ISSUE TITLE
I‘ve already set up this env and 'make' successfuly , but here comes the problem : tensorflow.python.framework.errors_impl.NotFoundError: /home/fudan/Desktop/wsl/DeepUPE/main/lib/hdrnet_ops.so: undefined symbol: _ZTIN10tensorflow8OpKernelE. What's going on?

### ISSUE THREAD

**Issue by Shunli-Wang** [wangruixing/DeepUPE#39]
here is the error:
(env_DeepUPE) fudan@fudan-DGX-Station:~/Desktop/wsl/DeepUPE$ python main/run.py checkpoints /home/fudan/Desktop/wsl/DeepUPE/input/o.jpg /home/fudan/Desktop/wsl/DeepUPE/output/
Traceback (most recent call last):
  File "main/run.py", line 30, in <module>
    import models as models
  File "/home/fudan/Desktop/wsl/DeepUPE/main/models.py", line 21, in <module>
    from layers import (conv, fc, bilateral_slice_apply)
  File "/home/fudan/Desktop/wsl/DeepUPE/main/layers.py", line 20, in <module>
    import hdrnet_ops
  File "/home/fudan/Desktop/wsl/DeepUPE/main/hdrnet_ops.py", line 28, in <module>
    _hdrnet = tf.load_op_library('/home/fudan/Desktop/wsl/DeepUPE/main/lib/hdrnet_ops.so')
  File "/home/fudan/Desktop/wsl/DeepUPE/env_DeepUPE/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/fudan/Desktop/wsl/DeepUPE/main/lib/hdrnet_ops.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

**Comment by jiangxuetao0823** [comment]
python 2.7 is needed

**Comment by yinyulin** [comment]
my python is 2.7, but i get the same error
Traceback (most recent call last):
  File "main/run.py", line 30, in <module>
    import models as models
  File "/home/yunkepan/DeepUPE/main/models.py", line 21, in <module>
    from layers import (conv, fc, bilateral_slice_apply)
  File "/home/yunkepan/DeepUPE/main/layers.py", line 20, in <module>
    import hdrnet_ops
  File "/home/yunkepan/DeepUPE/main/hdrnet_ops.py", line 27, in <module>
    _hdrnet = tf.load_op_library(path)
  File "/home/yunkepan/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/yunkepan/DeepUPE/main/lib/hdrnet_ops.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

**Comment by YUSHENWU** [comment]
Something like your GPUDevice is unavailable, not the same as when you make lib

**Comment by stezarpriansya** [comment]
hello, anyone can help?

**Comment by pxEkin** [comment]
need to link libtensorflow_framework.so

**Comment by yinyulin** [comment]
> need to link libtensorflow_framework.so
thankyou for your replay，I solved it by add
CFLAGS = -ltensorflow_framework
in Makefile

**Comment by pxEkin** [comment]
> > need to link libtensorflow_framework.so
> > thankyou for your replay，I solved it by add
> > CFLAGS = -ltensorflow_framework
> > in Makefile

You might get another error, like "undefined symbol: _ZN10tensorflow15OpKernelContext21CtxFailureWithWarningENS_6StatusE",  right??

**Comment by yinyulin** [comment]
> > > need to link libtensorflow_framework.so
> > > thankyou for your replay，I solved it by add
> > > CFLAGS = -ltensorflow_framework
> > > in Makefile
> 
> You might get another error, like "undefined symbol: _ZN10tensorflow15OpKernelContext21CtxFailureWithWarningENS_6StatusE", right??

sorry I do not get the error above, but I got another error undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv,  I solved it by change -D_GLIBCXX_USE_CXX11_ABI=0, hopes it help

**Comment by pxEkin** [comment]
> > > > need to link libtensorflow_framework.so
> > > > thankyou for your replay，I solved it by add
> > > > CFLAGS = -ltensorflow_framework
> > > > in Makefile
> > 
> > 
> > You might get another error, like "undefined symbol: _ZN10tensorflow15OpKernelContext21CtxFailureWithWarningENS_6StatusE", right??
> 
> sorry I do not get the error above, but I got another error undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv, I solved it by change -D_GLIBCXX_USE_CXX11_ABI=0, hopes it help

now， you can run and get right result？

**Comment by yinyulin** [comment]
> > > > > need to link libtensorflow_framework.so
> > > > > thankyou for your replay，I solved it by add
> > > > > CFLAGS = -ltensorflow_framework
> > > > > in Makefile
> > > 
> > > 
> > > You might get another error, like "undefined symbol: _ZN10tensorflow15OpKernelContext21CtxFailureWithWarningENS_6StatusE", right??
> > 
> > 
> > sorry I do not get the error above, but I got another error undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv, I solved it by change -D_GLIBCXX_USE_CXX11_ABI=0, hopes it help
> 
> now， you can run and get right result？

yes

**Comment by xiaonaa** [comment]
> > > > > > need to link libtensorflow_framework.so
> > > > > > thankyou for your replay，I solved it by add
> > > > > > CFLAGS = -ltensorflow_framework
> > > > > > in Makefile
> > > > 
> > > > 
> > > > You might get another error, like "undefined symbol: _ZN10tensorflow15OpKernelContext21CtxFailureWithWarningENS_6StatusE", right??
> > > 
> > > 
> > > sorry I do not get the error above, but I got another error undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv, I solved it by change -D_GLIBCXX_USE_CXX11_ABI=0, hopes it help
> > 
> > 
> > now， you can run and get right result？
> 
> yes

hello,Did you change CFLAGS = -fPIC -I$(TF_INC) -O2 -D_GLIBCXX_USE_CXX11_ABI=0 to CFLAGS = -ltensorflow_framework -D_GLIBCXX_USE_CXX11_ABI=0?

**Comment by aaaaangel** [comment]
> > > need to link libtensorflow_framework.so
> > > thankyou for your replay，I solved it by add
> > > CFLAGS = -ltensorflow_framework
> > > in Makefile
> 
> You might get another error, like "undefined symbol: _ZN10tensorflow15OpKernelContext21CtxFailureWithWarningENS_6StatusE", right??

hello, I follow the steps you just said and got this error, "undefined symbol: _ZN10tensorflow15OpKernelContext21CtxFailureWithWarningENS_6StatusE". Could you please tell me then what should I do?

**Comment by aasharma90** [comment]
Hi, 

Anybody who has got it working can please share a few details? For e.g, the version of TensorFlow,, the Makefile, etc.? Despite getting the make process without any errors, and trying numerous workarounds available on internet, I'm still facing the same runtime problem -

I'm presently using TensorFlow1.4, Python2.7 and CUDA9.0

Make output -
![image](https://user-images.githubusercontent.com/27413823/79078225-5e7bc900-7d39-11ea-96f6-54b4c65311c9.png)

Runtime error -
![image](https://user-images.githubusercontent.com/27413823/79078207-3b511980-7d39-11ea-8fa4-772c5351efca.png)

Thanks in advance!

**Comment by wenlerrr** [comment]
@aasharma90 Hello, I am facing the same issue too, did u solve it in the end?

**Comment by aasharma90** [comment]
Hi @wenlerrr, 

No, I couldn't get it working.
