### ISSUE TITLE
about more infomation

### ISSUE THREAD

**Issue by trialbox** [wangruixing/DeepUPE#66]
my env is ubuntu 18.04  python 3.6  cuda 10.1 cudnn7.6 gcc/g++ 7/6/5  tensorflow 1.15.
`-L$(TF_LIB) -ltensorflow_framework` added in makefile,and compiled .os is ok.but always has error.

`
/home/liruidev/.conda/envs/tf1gpu/bin/python /home/liruidev/PycharmProjects/DeepUPE-master/main/run.py ../checkpoints ../test/1.jpg ../test/1.out.jpg
WARNING:tensorflow:From /home/liruidev/PycharmProjects/DeepUPE-master/main/hdrnet_ops.py:24: The name tf.resource_loader.get_path_to_datafile is deprecated. Please use tf.compat.v1.resource_loader.get_path_to_datafile instead.

2020-02-12 23:26:08.967063: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

[16029] INFO run.py:55 | Single input ../test/1.jpg
WARNING:tensorflow:From /home/liruidev/PycharmProjects/DeepUPE-master/main/run.py:65: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

[16029] WARNING module_wrapper.py:139 | From /home/liruidev/PycharmProjects/DeepUPE-master/main/run.py:65: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/liruidev/PycharmProjects/DeepUPE-master/main/run.py:67: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

[16029] WARNING module_wrapper.py:139 | From /home/liruidev/PycharmProjects/DeepUPE-master/main/run.py:67: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-02-12 23:26:09.366214: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-02-12 23:26:09.371102: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2693770000 Hz
2020-02-12 23:26:09.371423: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f781b47bf0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-02-12 23:26:09.371441: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-02-12 23:26:09.372277: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-02-12 23:26:09.383083: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-12 23:26:09.383910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 960M major: 5 minor: 0 memoryClockRate(GHz): 1.176
pciBusID: 0000:01:00.0
2020-02-12 23:26:09.383951: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-12 23:26:09.385097: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-02-12 23:26:09.385945: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-02-12 23:26:09.386174: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-02-12 23:26:09.387411: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-02-12 23:26:09.388353: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-02-12 23:26:09.391457: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-12 23:26:09.391613: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-12 23:26:09.392531: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-12 23:26:09.393316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-12 23:26:09.642122: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-12 23:26:09.642150: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-02-12 23:26:09.642156: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-02-12 23:26:09.642368: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-12 23:26:09.642904: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-12 23:26:09.643497: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-12 23:26:09.643970: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1741 MB memory) -> physical GPU (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0)
2020-02-12 23:26:09.645229: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f7832944a0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-02-12 23:26:09.645251: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 960M, Compute Capability 5.0
[16029] INFO run.py:74 | Loading graph from ../checkpoints/model.ckpt.meta
WARNING:tensorflow:From /home/liruidev/PycharmProjects/DeepUPE-master/main/run.py:75: The name tf.train.import_meta_graph is deprecated. Please use tf.compat.v1.train.import_meta_graph instead.

[16029] WARNING module_wrapper.py:139 | From /home/liruidev/PycharmProjects/DeepUPE-master/main/run.py:75: The name tf.train.import_meta_graph is deprecated. Please use tf.compat.v1.train.import_meta_graph instead.

WARNING:tensorflow:The saved meta_graph is possibly from an older release:
'model_variables' collection should be of type 'byte_list', but instead is of type 'node_list'.
[16029] WARNING meta_graph.py:887 | The saved meta_graph is possibly from an older release:
'model_variables' collection should be of type 'byte_list', but instead is of type 'node_list'.
WARNING:tensorflow:From /home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/training/queue_runner_impl.py:391: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
[16029] WARNING deprecation.py:323 | From /home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/training/queue_runner_impl.py:391: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/liruidev/PycharmProjects/DeepUPE-master/main/utils.py:20: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

[16029] WARNING module_wrapper.py:139 | From /home/liruidev/PycharmProjects/DeepUPE-master/main/utils.py:20: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From /home/liruidev/PycharmProjects/DeepUPE-master/main/run.py:85: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

[16029] WARNING module_wrapper.py:139 | From /home/liruidev/PycharmProjects/DeepUPE-master/main/run.py:85: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:From /home/liruidev/PycharmProjects/DeepUPE-master/main/run.py:87: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

[16029] WARNING module_wrapper.py:139 | From /home/liruidev/PycharmProjects/DeepUPE-master/main/run.py:87: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/liruidev/PycharmProjects/DeepUPE-master/main/run.py:90: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

[16029] WARNING module_wrapper.py:139 | From /home/liruidev/PycharmProjects/DeepUPE-master/main/run.py:90: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/liruidev/PycharmProjects/DeepUPE-master/main/layers.py:52: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

[16029] WARNING module_wrapper.py:139 | From /home/liruidev/PycharmProjects/DeepUPE-master/main/layers.py:52: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From /home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
[16029] WARNING deprecation.py:323 | From /home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/liruidev/PycharmProjects/DeepUPE-master/main/models.py:182: The name tf.add_to_collection is deprecated. Please use tf.compat.v1.add_to_collection instead.

[16029] WARNING module_wrapper.py:139 | From /home/liruidev/PycharmProjects/DeepUPE-master/main/models.py:182: The name tf.add_to_collection is deprecated. Please use tf.compat.v1.add_to_collection instead.

WARNING:tensorflow:From /home/liruidev/PycharmProjects/DeepUPE-master/main/models.py:196: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

[16029] WARNING module_wrapper.py:139 | From /home/liruidev/PycharmProjects/DeepUPE-master/main/models.py:196: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py:180: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
[16029] WARNING deprecation.py:506 | From /home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py:180: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
WARNING:tensorflow:From /home/liruidev/PycharmProjects/DeepUPE-master/main/run.py:94: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

[16029] WARNING module_wrapper.py:139 | From /home/liruidev/PycharmProjects/DeepUPE-master/main/run.py:94: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

2020-02-12 23:26:11.589389: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-12 23:26:11.589957: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 960M major: 5 minor: 0 memoryClockRate(GHz): 1.176
pciBusID: 0000:01:00.0
2020-02-12 23:26:11.590044: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-12 23:26:11.590099: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-02-12 23:26:11.590144: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-02-12 23:26:11.590182: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-02-12 23:26:11.590216: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-02-12 23:26:11.590250: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-02-12 23:26:11.590315: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-12 23:26:11.590422: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-12 23:26:11.590970: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-12 23:26:11.591409: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-12 23:26:11.591438: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-12 23:26:11.591445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-02-12 23:26:11.591450: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-02-12 23:26:11.591566: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-12 23:26:11.592073: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-12 23:26:11.592525: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1741 MB memory) -> physical GPU (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0)
[16029] INFO run.py:97 | Restoring weights from ../checkpoints/model.ckpt
[16029] INFO run.py:102 | Processing ../test/1.jpg
2020-02-12 23:26:12.375193: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-02-12 23:26:12.546922: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
Traceback (most recent call last):
  File "/home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Failed to launch BilateralSliceApplyKernel.
	 [[{{node inference/output/slice/BilateralSliceApply}}]]
  (1) Internal: Failed to launch BilateralSliceApplyKernel.
	 [[{{node inference/output/slice/BilateralSliceApply}}]]
	 [[Cast/_111]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liruidev/PycharmProjects/DeepUPE-master/main/run.py", line 146, in <module>
    main(args)
  File "/home/liruidev/PycharmProjects/DeepUPE-master/main/run.py", line 127, in main
    out_ = sess.run(output, feed_dict=feed_dict)
  File "/home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Failed to launch BilateralSliceApplyKernel.
	 [[node inference/output/slice/BilateralSliceApply (defined at /home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
  (1) Internal: Failed to launch BilateralSliceApplyKernel.
	 [[node inference/output/slice/BilateralSliceApply (defined at /home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[Cast/_111]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'inference/output/slice/BilateralSliceApply':
  File "/home/liruidev/PycharmProjects/DeepUPE-master/main/run.py", line 146, in <module>
    main(args)
  File "/home/liruidev/PycharmProjects/DeepUPE-master/main/run.py", line 92, in main
    t_lowres_input, t_fullres_input, model_params, is_training=False)
  File "/home/liruidev/PycharmProjects/DeepUPE-master/main/models.py", line 56, in inference
    fullres_input, guide, bilateral_coeffs)
  File "/home/liruidev/PycharmProjects/DeepUPE-master/main/models.py", line 238, in _output
    out = bilateral_slice_apply(coeffs, guide, im, has_offset=True, name='slice')
  File "/home/liruidev/PycharmProjects/DeepUPE-master/main/layers.py", line 148, in bilateral_slice_apply
    sliced = hdrnet_ops.bilateral_slice_apply(grid, guide, input_image, has_offset=has_offset)
  File "<string>", line 256, in bilateral_slice_apply
  File "/home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/liruidev/.conda/envs/tf1gpu/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

malloc_consolidate(): invalid chunk size

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
`

So,what you cuda cudann more infomation,and include file?

**Comment by wangruixing** [comment]
Please use python2.7,  tf1.1 cuda-8.0

**Comment by trialbox** [comment]
> Please use python2.7, tf1.1 cuda-8.0

It is run.
My full env:
Ubuntu18.04
cuda8(setup by " .run" file, it could be install with other version in one system)
gcc g++ 4.8 .  (cuda8 and g++ 4.8 is must be required for compile "make" .so file)

In my system, "requirement.txt" is edited to this.

```
setproctitle==1.1.10
numpy==1.12.0
python-gflags==3.1.1
tensorflow-gpu==1.1.0
cudatoolkit==8.0
scikit-image==0.10
pyglib==0.1
python-magic==0.4.13

```
There is only install by pip, anaconda has package conflict.
If cudatoolkit==8.0 install by anaconda is only run code,can't make *.so.
multi-version could be manage by "update-alternatives --config cuda".

**Comment by trialbox** [comment]
@wangruixing 
I hope you can give us the training method and code as soon as possible.

Wish ‘deepue' project more and more famous
